name: Publish to NPM registry

on:
  release:
    types: [created]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.7.0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.com/

      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get git head
        run: echo "GIT_HEAD=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build
        run: |
          pnpm i --frozen-lockfile
          TAG_VERSION=${{ env.TAG_VERSION }} GIT_HEAD=${{ env.GIT_HEAD }} pnpm update:version
          pnpm build
        env:
          TAG_VERSION: ${{env.TAG_VERSION}}
          GIT_HEAD: ${{env.GIT_HEAD}}
          FORCE_COLOR: 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Publish
        run: npm publish ./dist/vue-cesium --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
